name: Hello World Workflow
on:
 workflow_dispatch:  # Enables manual trigger
jobs:
 say-hello:
   runs-on: self-hosted  # Use 'self-hosted' for custom runner or 'ubuntu-latest' for GitHub-hosted runner
   steps:
     - name: Print Hello World
       run: echo "Hello, World!"
