name: Terraform EC2 Provisioning

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted  # Use the self-hosted runner
    
    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"  # Replace with your required version
          terraform_wrapper: false  # Disable wrapper to avoid conflicts

      # Ensure Execution Policy is set to allow scripts to run on Windows
      - name: Set Execution Policy for PowerShell
        run: Set-ExecutionPolicy Unrestricted -Scope Process -Force

      # Verify Terraform binary exists and is executable
      - name: Verify Terraform Binary
        run: |
          echo "Checking Terraform version..."
          terraform -version

      # Terraform Initialization
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: "AKIA6GBMETA5YUZID2ZM"
          AWS_SECRET_ACCESS_KEY: "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"
      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: "AKIA6GBMETA5YUZID2ZM"
          AWS_SECRET_ACCESS_KEY: "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"
      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "AKIA6GBMETA5YUZID2ZM"
          AWS_SECRET_ACCESS_KEY: "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"

